# Generated by Django 3.1.5 on 2021-01-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_auto_20210115_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
